// @ts-nocheck -- auto generated by docstra
import * as d0 from '../../docs/02-quick-start/01-index.mdx?docstra';
import * as d1 from '../../docs/02-quick-start/02-subpage.mdx?docstra';
import * as d2 from '../../docs/index.mdx?docstra';

export const docs = [
    {
        slug: 'quick-start',
        path: '02-quick-start/01-index.mdx',
        data: {
            metadata: d0.metadata,
            raw: d0.raw,
            tableOfContents: d0.tableOfContents,
            body: d0.body,
            lastUpdated: d0.lastUpdated,
        },
    },
    {
        slug: 'quick-start/subpage',
        path: '02-quick-start/02-subpage.mdx',
        data: {
            metadata: d1.metadata,
            raw: d1.raw,
            tableOfContents: d1.tableOfContents,
            body: d1.body,
            lastUpdated: d1.lastUpdated,
        },
    },
    {
        slug: '',
        path: 'index.mdx',
        data: {
            metadata: d2.metadata,
            raw: d2.raw,
            tableOfContents: d2.tableOfContents,
            body: d2.body,
            lastUpdated: d2.lastUpdated,
        },
    },
];
