// @ts-nocheck -- auto generated by docstra
import * as d0 from '../../docs/01-index.mdx?docstra';
import * as d1 from '../../docs/02-getting-started.mdx?docstra';
import * as d2 from '../../docs/03-usage/01-generate.mdx?docstra';
import * as d3 from '../../docs/03-usage/02-validate.mdx?docstra';
import * as d4 from '../../docs/03-usage/03-watch.mdx?docstra';
import * as d5 from '../../docs/04-configuration.mdx?docstra';

export const docs = [
    {
        slug: '',
        path: '01-index.mdx',
        data: {
            metadata: d0.metadata,
            raw: d0.raw,
            tableOfContents: d0.tableOfContents,
            body: d0.body,
            lastUpdated: d0.lastUpdated,
        },
    },
    {
        slug: 'getting-started',
        path: '02-getting-started.mdx',
        data: {
            metadata: d1.metadata,
            raw: d1.raw,
            tableOfContents: d1.tableOfContents,
            body: d1.body,
            lastUpdated: d1.lastUpdated,
        },
    },
    {
        slug: 'usage/generate',
        path: '03-usage/01-generate.mdx',
        data: {
            metadata: d2.metadata,
            raw: d2.raw,
            tableOfContents: d2.tableOfContents,
            body: d2.body,
            lastUpdated: d2.lastUpdated,
        },
    },
    {
        slug: 'usage/validate',
        path: '03-usage/02-validate.mdx',
        data: {
            metadata: d3.metadata,
            raw: d3.raw,
            tableOfContents: d3.tableOfContents,
            body: d3.body,
            lastUpdated: d3.lastUpdated,
        },
    },
    {
        slug: 'usage/watch',
        path: '03-usage/03-watch.mdx',
        data: {
            metadata: d4.metadata,
            raw: d4.raw,
            tableOfContents: d4.tableOfContents,
            body: d4.body,
            lastUpdated: d4.lastUpdated,
        },
    },
    {
        slug: 'configuration',
        path: '04-configuration.mdx',
        data: {
            metadata: d5.metadata,
            raw: d5.raw,
            tableOfContents: d5.tableOfContents,
            body: d5.body,
            lastUpdated: d5.lastUpdated,
        },
    },
];
