import Link from 'next/link';

export default function Page() {
    return (
        <main className="flex flex-col items-center justify-center h-screen bg-gray-50 px-4 text-center">
            <h1 className="text-4xl font-semibold text-gray-800 mb-4">
                This is generated by create-docstra-app
            </h1>

            <h3 className="text-lg text-gray-600 mb-8">
                You can start writing your documentation.
            </h3>

            <Link
                href="/docs"
                className="px-6 py-2 text-white bg-blue-600 hover:bg-blue-700 rounded-lg shadow transition"
            >
                Go to Docs
            </Link>
        </main>
    );
}
